FROM aranasoft.azurecr.io/aranasoft/nginx-php:7.4

LABEL maintainer="Arana Software <hello@aranasoft.com>"

COPY config/ /var/www/html/config/
COPY vendor/ /var/www/html/vendor/
COPY web/ /var/www/html/web/
